# Tepora Project - Task Runner Configuration
# https://taskfile.dev
#
# Usage:
#   task dev          - Start both backend and frontend
#   task test         - Run all tests
#   task lint         - Run linters
#   task build-sidecar - Build PyInstaller sidecar

version: '3'

vars:
  BACKEND_DIR: backend-rs
  FRONTEND_DIR: frontend

tasks:
  # === Default ===
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  # === Development ===
  dev:
    desc: "Start both backend and frontend in development mode (port + token synchronized)"
    cmds:
      - task: dev-sync

  dev-backend:
    desc: "Start backend server"
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - cargo run

  dev-frontend:
    desc: "Start frontend dev server"
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run dev

  dev-sync:
    desc: "Start backend and frontend with dynamic port synchronization"
    cmds:
      - node scripts/dev_sync.mjs

  dev-tauri:
    desc: "Start Tauri app in dev mode"
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run tauri dev

  # === Testing ===
  test:
    desc: "Run all tests"
    cmds:
      - task: test-backend
      - task: test-frontend

  test-backend:
    desc: "Run backend tests"
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - cargo test

  test-frontend:
    desc: "Run frontend tests"
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run test

  # === Linting ===
  lint:
    desc: "Run all linters"
    cmds:
      - task: lint-backend
      - task: lint-frontend

  lint-backend:
    desc: "Lint backend code with rustfmt + clippy"
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - cargo fmt -- --check
      - cargo clippy -- -D warnings

  lint-frontend:
    desc: "Lint frontend code"
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run lint

  # === Type Checking ===
  typecheck:
    desc: "Run type checking"
    cmds:
      - task: typecheck-backend
      - task: typecheck-frontend

  typecheck-backend:
    desc: "Type check backend with cargo"
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - cargo check

  typecheck-frontend:
    desc: "Type check frontend"
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npx tsc --noEmit

  # === Quality Gate ===
  quality:
    desc: "Run all quality checks (backend + frontend)"
    cmds:
      - task: quality:backend
      - task: quality:frontend

  quality:strict:
    desc: "Run strict quality checks (warnings = failures)"
    cmds:
      - task: quality:backend
      - task: quality:frontend

  quality:fix:
    desc: "Run quality checks with auto-fix"
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - cargo fmt
      - cargo clippy -- -D warnings
      - cargo test

  quality:backend:
    desc: "Run backend quality checks only"
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - cargo fmt -- --check
      - cargo clippy -- -D warnings
      - cargo test

  quality:frontend:
    desc: "Run frontend quality checks only"
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run typecheck
      - npx biome check src/
      - npm run lint
      - npm test -- --run

  # === Security ===
  security:
    desc: "Run security scans (cargo audit, npm audit)"
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - cargo generate-lockfile
      - cargo audit
      - npm audit --audit-level=moderate --prefix {{.FRONTEND_DIR}}

  security-backend:
    desc: "Run backend security scan (cargo-audit)"
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - cargo generate-lockfile
      - cargo audit

  security-frontend:
    desc: "Run frontend security scan (npm audit)"
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm audit --audit-level=moderate

  # === Build ===
  build:
    desc: "Build both backend sidecar and frontend"
    cmds:
      - task: build-sidecar
      - task: build-frontend

  build-sidecar:
    desc: "Build Rust sidecar for Tauri"
    cmds:
      - node scripts/build_sidecar.mjs

  build-frontend:
    desc: "Build frontend for production"
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run build

  # === Installation ===
  install:
    desc: "Install all dependencies"
    cmds:
      - task: install-backend
      - task: install-frontend

  install-backend:
    desc: "Fetch backend dependencies"
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - cargo fetch

  install-frontend:
    desc: "Install frontend dependencies"
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm install

  # === Cleanup ===
  clean:
    desc: "Clean build artifacts"
    cmds:
      - task: clean-backend
      - task: clean-frontend

  clean-backend:
    desc: "Clean backend build artifacts"
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - cargo clean

  clean-frontend:
    desc: "Clean frontend build artifacts"
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - cmd: rm -rf dist node_modules/.cache
        platforms: [linux, darwin]
      - cmd: if exist dist rmdir /s /q dist
        platforms: [windows]
