"""Quick smoke check of the self-contained preview: the screens open, the sample work runs, memory
can be edited, settings forms validate input, and narrow screens do not overflow. No AI is used."""
from playwright.sync_api import sync_playwright
import json,pathlib,os,shutil
root=pathlib.Path(__file__).resolve().parents[1]
base=root/'.qa';base.mkdir(exist_ok=True)
html=(root/'tepora-v3-preview.html').read_text()
with sync_playwright() as p:
    executable=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium') or shutil.which('google-chrome')
    browser=p.chromium.launch(**({'executable_path':executable} if executable else {}),headless=True,args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1512,'height':1000},device_scale_factor=1,timezone_id='Asia/Tokyo')
    page.set_default_timeout(6000)
    errors=[];warnings=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('console',lambda msg:warnings.append(msg.text) if msg.type=='error' else None)
    def nav(view):page.locator(f'.nav [data-view={view}]').click()
    # Browser URL navigation is blocked by managed policy. Do not disable that policy.
    # Render supplied source in memory; real localhost transport is tested with node:test.
    page.set_content(html,wait_until='load')
    page.locator('#clock-display').wait_for()
    assert page.title().startswith('Tepora')
    assert page.locator('#composer-input').is_visible()
    page.screenshot(path=str(base/'01-home.png'))
    nav('workspace')
    page.get_by_role('button',name='画面サンプルを試す',exact=True).click()
    page.wait_for_function("document.querySelector('.version-button')?.textContent.includes('3')")
    frame=page.frame_locator('#artifact-preview iframe')
    assert '余白から' in frame.locator('h1').inner_text()
    page.screenshot(path=str(base/'02-work.png'))
    nav('memory')
    page.get_by_role('button',name='記憶を追加',exact=True).click()
    page.locator('[name="title"]').fill('作業の進め方')
    page.locator('[name="content"]').fill('結論を先に伝えてほしい。成果物は早めに見せて、途中でも相談してほしい。')
    page.locator('#memory-form button[type="submit"]').click()
    page.wait_for_timeout(250)
    assert page.locator('.memory-card').count()==1
    page.locator('[data-action="memory-edit"]').click()
    page.locator('[name="content"]').fill('結論を先に。提案には根拠と反対意見も添えてほしい。')
    page.locator('#memory-form button[type="submit"]').click()
    page.wait_for_timeout(250)
    assert '反対意見' in page.locator('.memory-card p').inner_text()
    page.screenshot(path=str(base/'03-memory.png'))
    nav('settings')
    page.get_by_role('button',name='道具を1件追加',exact=True).click()
    page.locator('[name="name"]').fill('Context Hub')
    page.locator('[name="command"]').fill('C:/Program Files/nodejs/node.exe')
    page.locator('[name="args"]').fill('["C:/hub/dist/cli.js", "serve"]')
    page.locator('#mcp-form button[type="submit"]').click()
    page.wait_for_timeout(200)
    assert 'Context Hub' in page.locator('.settings-page').inner_text()
    page.get_by_role('button',name='YouTubeを流す',exact=True).click()
    page.locator('[name="url"]').fill('https://evil.example/watch?v=abcdefghijk')
    page.locator('#media-form button[type="submit"]').click()
    page.wait_for_timeout(100)
    assert 'YouTube' in page.locator('#toast').inner_text()
    assert page.locator('#media-player iframe').count()==0
    page.keyboard.press('Escape')
    if page.locator('.discard-bar').count():page.get_by_role('button',name='破棄して閉じる',exact=True).click()
    page.screenshot(path=str(base/'04-settings.png'))
    nav('workspace')
    page.locator('.bench-actions [data-action="task"]').click()
    page.locator('#panel-title').wait_for()
    page.screenshot(path=str(base/'05-task-detail.png'))
    page.keyboard.press('Escape')
    assert page.locator('#panel').is_hidden()
    nav('home')
    page.get_by_role('button',name='画面の表示',exact=True).click()
    page.get_by_role('button',name='待機画面にする',exact=True).click()
    page.wait_for_function("document.body.classList.contains('is-ambient')")
    page.screenshot(path=str(base/'06-ambient.png'))
    page.wait_for_timeout(1300)
    page.keyboard.press('Escape')
    page.wait_for_function("!document.body.classList.contains('is-ambient')")
    page.set_viewport_size({'width':390,'height':844})
    page.wait_for_timeout(200)
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1')
    page.screenshot(path=str(base/'07-home-mobile.png'),full_page=True)
    nav('settings')
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1')
    page.screenshot(path=str(base/'08-settings-mobile.png'),full_page=True)
    page.locator('#readiness').click()
    page.screenshot(path=str(base/'09-onboarding-mobile.png'))
    page.keyboard.press('Escape')
    nav('workspace')
    page.locator('.bench-actions [data-action="task"]').click()
    page.locator('#task-actions [data-action="cancel"]').click()
    page.wait_for_timeout(300)
    assert '取り消し' in page.locator('#task-status').inner_text()
    print('errors',errors,'console',warnings)
    assert not errors
    (base/'browser-results.json').write_text(json.dumps({'method':'Chromium set_content, supplied self-contained source (managed policy blocks URL navigation)','liveTransport':'tested separately with node:test; browser live URL not verified','pageErrors':errors,'consoleErrors':warnings,'viewports':['1512x1000','390x844'],'checks':['page identity and no blank screen','artifact three revisions rendered in sandbox iframe','memory create/edit','MCP add (preview config only)','media invalid URL rejected','task detail panel and Escape','idle screen and wake by key','mobile no horizontal overflow','onboarding','cancel task']},ensure_ascii=False,indent=2))
    browser.close()
