from playwright.sync_api import sync_playwright
import json,pathlib,os
root=pathlib.Path(__file__).resolve().parents[1]
base=root/'.qa';base.mkdir(exist_ok=True)
html=(root/'tepora-v3-preview.html').read_text()
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH'),headless=True,args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1512,'height':1000},device_scale_factor=1,timezone_id='Asia/Tokyo')
    errors=[];warnings=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('console',lambda msg:warnings.append(msg.text) if msg.type=='error' else None)
    # Browser URL navigation is blocked by managed policy. Do not disable that policy.
    # Render supplied source in memory; real localhost transport is tested with node:test.
    page.set_content(html,wait_until='load')
    page.wait_for_timeout(300)
    assert page.title()=='Tepora V3 — interactive preview'
    assert page.locator('h1').inner_text()=='今日を、もう少し自由に。'
    page.screenshot(path=str(base/'01-home-empty.png'))
    page.locator('[data-action="demo"]').click()
    page.wait_for_timeout(2800)
    assert page.locator('.studio-version').inner_text()=='rev. 03'
    assert '完了' in page.locator('.task-status').inner_text()
    frame=page.frame_locator('#artifact-preview iframe')
    assert '余白から' in frame.locator('h1').inner_text()
    page.screenshot(path=str(base/'02-home-desktop.png'))
    page.locator('.rail-item[data-view="memory"]').click()
    page.locator('[data-action="memory-add"]').first.click()
    page.locator('[name="title"]').fill('作業の進め方')
    page.locator('[name="content"]').fill('結論を先に伝えてほしい。成果物は早めに見せて、途中でも相談してほしい。')
    page.locator('#memory-form button[type="submit"]').click()
    page.wait_for_timeout(250)
    assert page.locator('.memory-card').count()==1
    page.locator('[data-action="memory-edit"]').click()
    page.locator('[name="content"]').fill('結論を先に。提案には根拠と反対意見も添えてほしい。')
    page.locator('#memory-form button[type="submit"]').click()
    page.wait_for_timeout(250)
    assert '反対意見' in page.locator('.memory-card p').inner_text()
    page.screenshot(path=str(base/'03-memory.png'))
    page.locator('.rail-item[data-view="connections"]').click()
    page.screenshot(path=str(base/'04-connections.png'))
    page.locator('[data-action="mcp-add"]').click()
    page.locator('[name="name"]').fill('Context Hub')
    page.locator('[name="command"]').fill('C:/Program Files/nodejs/node.exe')
    page.locator('[name="args"]').fill('["C:/hub/dist/cli.js", "serve"]')
    page.locator('#mcp-form button[type="submit"]').click()
    page.wait_for_timeout(200)
    assert 'Context Hub' in page.locator('.page-view').inner_text()
    page.locator('[data-action="skill-add"]').click()
    page.locator('[name="name"]').fill('短い報告')
    page.locator('[name="description"]').fill('最初に結論をまとめる')
    page.locator('[name="content"]').fill('# 短い報告\n結論、根拠、次の行動。')
    page.locator('#skill-form button[type="submit"]').click()
    page.wait_for_timeout(200)
    assert '短い報告' in page.locator('.page-view').inner_text()
    page.locator('[data-action="settings"]').first.click()
    page.locator('#overlay [data-action="settings"][data-section="voice"]').click()
    assert page.locator('[name="asrModel"]').input_value()=='Qwen/Qwen3-ASR-1.7B'
    page.locator('#overlay [data-action="settings"][data-section="appearance"]').click()
    page.locator('[name="companion"]').fill('Tepora')
    page.locator('#settings-form button[type="submit"]').click()
    page.wait_for_timeout(200)
    page.locator('.rail-item[data-view="home"]').click()
    page.locator('[data-action="task"]').click()
    page.screenshot(path=str(base/'05-task-detail.png'))
    page.keyboard.press('Escape')
    page.locator('[data-action="media"]').first.click()
    page.locator('[name="url"]').fill('https://evil.example/watch?v=abcdefghijk')
    page.locator('#media-form button[type="submit"]').click()
    page.wait_for_timeout(100)
    assert 'YouTube' in page.locator('#toast').inner_text()
    assert page.locator('#media-embed iframe').count()==0
    page.keyboard.press('Escape')
    page.locator('[data-action="focus"]').click()
    assert '集中 25:' in page.locator('#focus-label').inner_text()
    page.locator('[data-action="ambient"]').click()
    assert 'ambient-mode' in page.locator('body').get_attribute('class')
    page.screenshot(path=str(base/'09-ambient.png'))
    page.keyboard.press('Escape')
    assert 'ambient-mode' not in page.locator('body').get_attribute('class')
    page.set_viewport_size({'width':390,'height':844})
    page.wait_for_timeout(200)
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
    page.screenshot(path=str(base/'06-home-mobile.png'),full_page=True)
    page.locator('.rail-item[data-view="connections"]').click()
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
    page.screenshot(path=str(base/'07-connections-mobile.png'),full_page=True)
    page.locator('[data-action="onboard"]').click()
    page.screenshot(path=str(base/'10-onboarding-mobile.png'))
    page.keyboard.press('Escape')
    page.locator('.rail-item[data-view="workspace"]').click()
    page.locator('[data-action="demo"]').click()
    page.locator('[data-action="stop"]').first.click()
    page.wait_for_timeout(200)
    assert '停止' in page.locator('.task-status').first.inner_text()
    print('errors',errors,'console',warnings)
    assert not errors
    (base/'browser-results.json').write_text(json.dumps({'method':'Chromium set_content, supplied self-contained source (managed policy blocks URL navigation)','liveTransport':'tested separately with node:test; browser live URL not verified','pageErrors':errors,'consoleErrors':warnings,'viewports':['1512x1000','390x844'],'checks':['page identity and no blank screen','artifact three revisions rendered in sandbox iframe','memory create/edit','MCP add (preview config only)','skill add','voice and appearance settings','task detail','media invalid URL rejected','focus timer','ambient and Escape','mobile no horizontal overflow','onboarding','cancel task']},ensure_ascii=False,indent=2))
    browser.close()
