"""UI routing flows against the explicit self-contained preview, not real model calls."""
from pathlib import Path
import base64,json,os,shutil,sys
from playwright.sync_api import sync_playwright
root=Path(sys.argv[1]).resolve();out=Path(sys.argv[2]);out.mkdir(parents=True,exist_ok=True)
checks=[];errors=[]
with sync_playwright() as p:
 executable=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium')
 browser=p.chromium.launch(**({'executable_path':executable} if executable else {}),headless=True,args=['--no-sandbox'])
 page=browser.new_page(viewport={'width':1440,'height':1000},color_scheme='light',timezone_id='Asia/Tokyo')
 page.set_default_timeout(6000)
 page.on('pageerror',lambda error:errors.append(str(error)))
 page.set_content((root/'tepora-v3-preview.html').read_text(),wait_until='load')
 page.locator('#clock-display').wait_for()
 assert page.title().startswith('Tepora')
 page.screenshot(path=str(out/'01-home.png'))
 def providers():
  page.get_by_role('button',name='設定',exact=True).click()
  page.locator('[data-action=providers-launch]').first.click()
  page.get_by_role('dialog',name='知能と通信の使い分け').wait_for()
 def shared():
  page.get_by_role('button',name='画面の表示',exact=True).click()
  page.get_by_role('button',name='共有表示（個人の内容を隠す）',exact=True).click()
 providers()
 assert 'ローカルの継続先を追加' in page.locator('.offline-floor').inner_text()
 def add(preset,id,name,model,vision=False,lan=False):
  page.get_by_role('button',name='接続先を追加',exact=True).click()
  page.locator('#provider-preset').select_option(preset)
  page.locator('#provider-form [name=id]').fill(id)
  page.locator('#provider-form [name=name]').fill(name)
  page.locator('#provider-form [name=model]').fill(model)
  page.locator('[name=cap-tools]').select_option('true')
  page.locator('[name=cap-vision]').select_option('true' if vision else 'false')
  if lan:
   page.locator('[name=domain]').select_option('lan')
   page.locator('[name=baseUrl]').fill('http://192.168.1.20:8000/v1')
   page.locator('[name=pinnedAddress]').fill('192.168.1.20')
   page.locator('[name=allowPlainHttp]').check()
  page.get_by_role('button',name='登録する',exact=True).click()
  page.get_by_role('dialog',name='知能と通信の使い分け').wait_for()
 add('ollama','local-backup','このPCの継続先（設定例）','local-model-example')
 add('lmstudio','local-vision','画像を読むローカルVLM（設定例）','vision-model-example',vision=True)
 add('openai','cloud-main','クラウドの主モデル（設定例）','cloud-model-example')
 add('vllm','lan-inference','指定したLAN推論機（設定例）','lan-model-example',lan=True)
 assert page.locator('.provider-list article').count()==4
 assert page.locator('select[name=vision] option[value=cloud-main]').count()==0
 page.locator('select[name=main]').select_option('cloud-main')
 page.locator('input[name=main-fallbacks]').fill('local-backup')
 page.locator('select[name=work]').select_option('cloud-main')
 page.locator('input[name=work-fallbacks]').fill('lan-inference, local-backup')
 page.locator('select[name=vision]').select_option('local-vision')
 page.locator('select[name=dictation]').select_option('local-backup')
 page.get_by_role('button',name='この経路を使う',exact=True).click()
 page.wait_for_function("document.querySelector('select[name=main]')?.value==='cloud-main'")
 assert page.locator('input[name=work-fallbacks]').input_value()=='lan-inference, local-backup'
 assert '確認済み' not in page.locator('.offline-floor').inner_text()
 checks.append('named device, cloud, LAN and vision profiles; explicit ordered fallbacks; capability-filtered choices; no invented probe success')
 page.screenshot(path=str(out/'02-providers.png'))
 page.locator('#route-form').scroll_into_view_if_needed()
 page.screenshot(path=str(out/'07-role-routing.png'))
 page.locator('.network-options').scroll_into_view_if_needed()
 page.get_by_role('dialog').get_by_role('button',name='完全オフライン',exact=True).click()
 page.wait_for_function("document.querySelector('[data-action=net-mode][data-value=offline]')?.getAttribute('aria-pressed')==='true'")
 assert page.locator('[data-mode=offline]').get_attribute('aria-pressed')=='true'
 assert 'OS全体のファイアウォールではありません' in page.get_by_role('dialog').inner_text()
 page.screenshot(path=str(out/'03-offline.png'))
 page.get_by_role('dialog').get_by_role('button',name='信頼LANだけ',exact=True).click()
 assert 'LAN全体は許可しません' in page.get_by_role('dialog').inner_text()
 checks.append('mode switches are explicit; offline scope and exact-LAN scope remain visible')
 # Credentials are not accepted or persisted by the preview.
 page.locator('[data-action=provider-key][data-id=cloud-main]').click()
 page.locator('[name=key]').fill('test-only-never-persist')
 page.get_by_role('button',name='この接続先だけに設定',exact=True).click()
 page.wait_for_function("document.querySelector('#toast').textContent.includes('プレビュー')")
 assert page.get_by_role('dialog',name='この接続先の認証').is_visible()
 page.keyboard.press('Escape')
 providers()
 assert page.locator('select[name=main]').input_value()=='cloud-main'
 checks.append('reopening settings preserves routing; offline preview refuses API key submission')
 page.keyboard.press('Escape')
 # Image attachment is user-selected and remains a draft until explicit send.
 page.get_by_role('button',name='ホーム',exact=True).click()
 png=base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j1ioAAAAASUVORK5CYII=')
 with page.expect_file_chooser() as chooser:page.get_by_role('button',name='ファイルを添える',exact=True).click()
 chooser.value.set_files({'name':'selected-image.png','mimeType':'image/png','buffer':png})
 page.get_by_text('selected-image.png',exact=True).wait_for()
 page.locator('#composer-input').fill('この画像をローカルで読み、要点をまとめて')
 assert 'まだAIへ送信' in page.locator('#toast').inner_text()
 page.screenshot(path=str(out/'04-image-draft.png'))
 shared()
 assert not page.locator('#input-files').is_visible()
 page.get_by_role('button',name='共有表示を終える',exact=True).click()
 assert 'selected-image.png' in page.locator('#input-files').inner_text()
 checks.append('explicit image attachment remains unsent; shared display hides filename and draft')
 page.get_by_role('button',name='設定',exact=True).click()
 page.locator('[data-action=computer-launch]').click()
 page.locator('#computer-form').wait_for()
 page.locator('#computer-form [name=enabled]').check()
 page.locator('#computer-form [name=python]').fill('python')
 page.locator('[name=origins]').fill('https://example.com')
 page.screenshot(path=str(out/'05-computer-settings.png'))
 page.get_by_role('button',name='設定を保存',exact=True).click()
 checks.append('explicit scoped Computer Use configuration; saving preview settings does not start any process')
 page.set_viewport_size({'width':390,'height':844})
 providers()
 assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1')
 page.screenshot(path=str(out/'06-mobile-providers.png'))
 page.keyboard.press('Escape')
 page.get_by_role('button',name='最大',exact=True).click()
 page.wait_for_function("document.documentElement.style.fontSize==='25.6px'")
 page.get_by_role('button',name='仕事',exact=True).click()
 page.get_by_role('button',name='画面サンプルを試す',exact=True).click()
 page.get_by_role('button',name='すべて停止',exact=True).wait_for()
 assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1')
 page.get_by_role('button',name='ホーム',exact=True).click()
 assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1')
 page.screenshot(path=str(out/'08-mobile-large-text.png'))
 checks.append('390px and 160% text keep the stop control reachable while work runs, without horizontal overflow')
 assert not errors,errors
 browser.close()
report={'mode':'self-contained UI preview','realModels':False,'browser':'system Chromium via Playwright; Browser plugin unavailable',
 'liveHTTP':'separate tests/routing-integration.test.mjs','viewports':[[1440,1000],[390,844]],'checks':checks,'errors':errors}
(out/'browser-routing.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
print(json.dumps(report,ensure_ascii=False,indent=2))
