import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {Store} from '../core/store.mjs';
import {Harness} from '../core/harness.mjs';
import {Connectors} from '../core/connectors.mjs';
import {Requests} from '../core/requests.mjs';
import {Dialogue} from '../core/dialogue.mjs';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<400;i++){if(fn())return;await delay(10);}assert.fail('state timeout');}
const call=(name,args,id=name)=>({role:'assistant',tool_calls:[{id,type:'function',function:{name,arguments:JSON.stringify(args)}}]});
async function fixture(t,chat){const dir=await mkdtemp(path.join(os.tmpdir(),'tepora-independent-')),store=new Store(dir);store.settings={...store.settings,model:'fixture',concurrency:2};const h=new Harness(store,new Connectors(store),{runtimeFactory:()=>({chat})}),d=new Dialogue(store,h,new Requests(store,h));t.after(async()=>{d.close();h.close();await until(()=>!h.active.size);store.close();await rm(dir,{recursive:true,force:true});});return {store,h,d};}
// Direct contract tests simulate a live foreground tool call; the final test exercises real runtime delegation.
async function delegate(f,p,args){f.h.update(p,{status:'running'});try{return await f.d.delegate(p,args);}finally{f.h.update(p,{status:'completed'});}}
function send(f,input){const s=f.d.session();return f.d.submit({requestId:randomUUID(),sessionId:s.id,sessionRevision:s.revision,input,contextConsent:f.d.context().id});}
test('independent: foreground completes while two workers remain blocked, persona and memory isolated',async t=>{const seen=[];const f=await fixture(t,async(m,opts)=>{seen.push(structuredClone(m));if(m[0].content.includes('subordinate background worker'))return await new Promise((res,rej)=>opts.signal.addEventListener('abort',()=>rej(opts.signal.reason),{once:true}));return {content:'character responsive'};});f.store.memory('PRIVATE_GLOBAL_SENTINEL');f.d.configure({expectedRevision:0,character:{name:'CHAR_ONLY',instructions:'gentle'},worker:{name:'WORK_ONLY',instructions:'precise'}});const p=send(f,'work1').job;await until(()=>f.store.get('job',p.id).status==='completed');await delegate(f,p,{input:'purpose1'});await delegate(f,p,{input:'purpose2'});await until(()=>f.h.active.size===2);const next=send(f,'hello again').job;await until(()=>f.store.get('job',next.id).status==='completed');assert.equal(f.h.active.size,2);const workers=seen.filter(m=>m[0].content.includes('subordinate background worker'));assert.equal(workers.length,2);for(const m of workers){assert.match(m[0].content,/You are WORK_ONLY/);assert.doesNotMatch(JSON.stringify(m),/PRIVATE_GLOBAL_SENTINEL/);}assert.equal(f.d.snapshot().messages.filter(m=>m.kind==='character').length,2);});
test('independent: followup reads bounded real worker output as tool evidence without focus',async t=>{let resultSeen=false;const f=await fixture(t,async m=>{if(m[0].content.includes('subordinate background worker'))return {content:'VERIFIED_RESULT_42'};const last=m.at(-1);if(last.role==='tool'){resultSeen=last.content.includes('VERIFIED_RESULT_42');assert.match(last.content,/untrusted/);return {content:resultSeen?'The result is 42':'no result'};}if(last.content==='どうだった？')return call('worker_status',{});return {content:'accepted'};});const p=send(f,'compute').job;await until(()=>f.store.get('job',p.id).status==='completed');const w=await delegate(f,p,{input:'compute'});await until(()=>f.store.get('job',w.jobId).status==='review');const next=send(f,'どうだった？').job;await until(()=>f.store.get('job',next.id).status==='completed');assert.ok(resultSeen);assert.equal(f.store.get('job',next.id).output,'The result is 42');assert.equal(f.store.value('companion'),null);});
test('independent: deterministic event IDs survive repeated reconcile and restart',async t=>{const f=await fixture(t,async()=>({content:'answer'}));const p=send(f,'hello').job;await until(()=>f.store.get('job',p.id).status==='completed');const w=await delegate(f,p,{input:'work'});await until(()=>f.store.get('job',w.jobId).status==='review');const before=f.store.list('dialogue-message').map(x=>x.id).sort();for(let i=0;i<4;i++)f.d.reconcile();f.d.close();f.d=new Dialogue(f.store,f.h,new Requests(f.store,f.h));assert.deepEqual(f.store.list('dialogue-message').map(x=>x.id).sort(),before);});
test('independent: pinned job personas unaffected by later changes',async t=>{const f=await fixture(t,async()=>({content:'answer'}));const p=send(f,'hello').job;await until(()=>f.store.get('job',p.id).status==='completed');f.d.configure({expectedRevision:0,worker:{name:'NEW_WORKER',instructions:'new'}});const w=await delegate(f,p,{input:'work'});assert.equal(f.store.get('job',w.jobId).personaSnapshot.worker.name,'Tepora Worker');assert.equal(f.store.get('job',w.jobId).personaSnapshot.revision,0);});
test('independent: question replies are exact-targeted and cancelled questions reject late answers',async t=>{const f=await fixture(t,async m=>{if(!m[0].content.includes('subordinate background worker'))return {content:'chat continues'};if(m.some(x=>x.role==='user'&&x.content.startsWith('追加指示:')))return {content:'ANSWERED_RIGHT_JOB'};return call('ask_user',{question:'Which value?'},'question-call');});const p=send(f,'scope').job;await until(()=>f.store.get('job',p.id).status==='completed');const a=await delegate(f,p,{input:'a'}),b=await delegate(f,p,{input:'b'});await until(()=>[a,b].every(w=>f.store.get('job',w.jobId).status==='paused')&&!f.h.active.size);const qa=f.store.list('worker-question').find(q=>q.jobId===a.jobId),qb=f.store.list('worker-question').find(q=>q.jobId===b.jobId);const body={requestId:randomUUID(),sessionId:f.d.session().id,questionId:qa.id,jobId:b.jobId,jobRevision:0,input:'42'};assert.throws(()=>f.d.reply(body),/質問/);const plain=send(f,'42').job;await until(()=>f.store.get('job',plain.id).status==='completed');assert.equal(f.store.get('worker-question',qa.id).status,'pending');const reply={...body,jobId:a.jobId};f.d.reply(reply);assert.equal(f.d.reply(reply).duplicate,true);await until(()=>f.store.get('job',a.jobId).status==='review');assert.equal(f.store.get('job',a.jobId).output,'ANSWERED_RIGHT_JOB');assert.equal(f.store.get('job',b.jobId).status,'paused');f.h.halt(b.jobId,'cancelled');assert.throws(()=>f.d.reply({...body,requestId:randomUUID(),questionId:qb.id}),/質問|停止/);});
test('independent: cross-recipient result denied and cancelled result no longer surfaced',async t=>{const f=await fixture(t,async()=>({content:'SECRET_RESULT'}));const p=send(f,'scope').job;await until(()=>f.store.get('job',p.id).status==='completed');const w=await delegate(f,p,{input:'work'});await until(()=>f.store.get('job',w.jobId).status==='review');assert.equal(f.d.workerStatus(p).workers[0].output,'SECRET_RESULT');const other={...p,runtime:{...p.runtime,model:'different-recipient'}};assert.ok(!JSON.stringify(f.d.workerStatus(other)).includes('SECRET_RESULT'));f.h.halt(w.jobId,'cancelled');assert.ok(!JSON.stringify(f.d.workerStatus(p)).includes('SECRET_RESULT'));});
test('independent: actual model tool delegation then followup obtains verified result',async t=>{let received=false;const f=await fixture(t,async m=>{if(m[0].content.includes('subordinate background worker'))return {content:'ACTUAL_WORKER_81'};const last=m.at(-1);if(last.role==='tool'&&last.tool_call_id==='delegate-live')return {content:'I am working on it'};if(last.role==='tool'&&last.tool_call_id==='read-live'){received=last.content.includes('ACTUAL_WORKER_81');return {content:received?'81 from worker':'no'};}if(last.content==='please calculate')return call('task_submit',{input:'calculate'},'delegate-live');if(last.content==='どうだった？')return call('worker_status',{},'read-live');return {content:'fallback'};});const first=send(f,'please calculate').job;await until(()=>f.store.get('job',first.id).status==='completed'&&f.store.list('job').some(j=>j.kind==='work'&&j.status==='review'));const next=send(f,'どうだった？').job;await until(()=>f.store.get('job',next.id).status==='completed');assert.ok(received);assert.equal(f.store.get('job',next.id).output,'81 from worker');assert.equal(f.store.list('job').filter(j=>j.kind==='work').length,1);});
test('independent: cross-recipient excerpt grant does not leak unapproved worker title',async t=>{const f=await fixture(t,async()=>({content:'APPROVED_EXCERPT'}));const p=send(f,'scope').job;await until(()=>f.store.get('job',p.id).status==='completed');const w=await delegate(f,p,{input:'work'});await until(()=>f.store.get('job',w.jobId).status==='review');const job=f.store.get('job',w.jobId);f.h.update(job,{runtime:{...job.runtime,model:'other-recipient'},title:'PRIVATE_UNAPPROVED_TITLE'});const preview=f.d.relayPreview(job.id);assert.ok(!JSON.stringify(preview).includes('PRIVATE_UNAPPROVED_TITLE'));f.d.relay({...preview,consent:true});const result=f.d.workerStatus(p);assert.equal(result.workers[0].output,'APPROVED_EXCERPT');assert.ok(!JSON.stringify(result).includes('PRIVATE_UNAPPROVED_TITLE'));});
