import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {Store} from '../core/store.mjs';
import {Harness} from '../core/harness.mjs';
import {Connectors} from '../core/connectors.mjs';
import {Requests} from '../core/requests.mjs';
import {Companion} from '../core/companion.mjs';
import {IntentProposals} from '../core/intent.mjs';
import {NetworkPolicy} from '../core/network-policy.mjs';
import {ProviderRegistry} from '../core/provider-registry.mjs';
const shape=(action='continue',targetJobId='one')=>({action,targetJobId,ambiguous:false,question:'',summary:'fixture'});
const reply=p=>({role:'assistant',tool_calls:[{id:'classification',type:'function',function:{name:'propose_intent',arguments:JSON.stringify(p)}}]});
const profile=id=>({id,name:id,protocol:'chat-completions',baseUrl:`http://127.0.0.1:${id==='first'?9001:9002}/v1`,model:id,domain:'device',capabilities:{text:true,tools:true}});
async function fixture(t){
 const dir=await mkdtemp(path.join(os.tmpdir(),'tepora-review-intent-')),store=new Store(dir);store.settings={...store.settings,model:'fixture'};
 const network=new NetworkPolicy(store,{lookup:async()=>{throw Error('No network permitted in fixture')},transport:async()=>{throw Error('No transport permitted in fixture')}});
 let answer=reply(shape()),messages,release=null;
 const runtime={chat:async(m)=>{messages=m;if(release)await release;return answer}};
 const registry=new ProviderRegistry(store,network,{clientFactory:()=>runtime});registry.save({profiles:[profile('first'),profile('second')],routes:{main:{primary:'first',fallbacks:[]}}},0);
 const h=new Harness(store,new Connectors(store,network),{network,registry,runtimeFactory:()=>runtime});h.pump=()=>{};
 const requests=new Requests(store,h),focus=new Companion(store),intents=new IntentProposals(store,h,requests);
 const route=registry.pin('chat');for(const id of ['one','two'])store.put('job',{id,input:id==='one'?'FOCUS_PURPOSE':'OTHER_PRIVATE_PURPOSE',title:id,kind:'chat',engine:'builtin',status:'paused',revision:0,instructions:[],runtime:registry.settingsFor(route),routeSnapshot:route,consentEpoch:0});
 store.put('message',{id:'private-other',jobId:'two',role:'user',content:'OTHER_PRIVATE_MESSAGE'});store.put('message',{id:'private-tool',jobId:'one',role:'tool',content:'FOCUS_TOOL_SECRET'});store.put('artifact',{id:'private-art',jobId:'one',content:'FOCUS_ARTIFACT_SECRET'});
 focus.focus('one',{expectedRevision:0});t.after(async()=>{h.close();registry.close();network.close();store.close();await rm(dir,{recursive:true,force:true});});
 return {store,h,requests,focus,intents,registry,setAnswer:a=>answer=a,messages:()=>messages,hold:()=>{let resolve;release=new Promise(r=>resolve=r);return resolve;}};
}
const propose=f=>f.intents.propose({requestId:'independent-proposal-001',input:'元の文章をそのまま訂正する',focusRevision:f.focus.snapshot().revision,consent:f.intents.publicContext().id});
for(const [name,p] of [['arbitrary target',shape('continue','two')],['engine override',{...shape(),engine:'codex'}],['approval command',{...shape(),allow:true}],['cancel action',shape('cancel','one')],['nonboolean ambiguity',{...shape(),ambiguous:'false'}],['oversized text',{...shape(),question:'x'.repeat(301)}],['prototype extra',JSON.parse('{"action":"continue","targetJobId":"one","ambiguous":false,"question":"","summary":"","__proto__":{"admin":true}}')]])test('independent rejects classifier '+name,async t=>{const f=await fixture(t);f.setAnswer(reply(p));await assert.rejects(propose(f));assert.equal(f.store.list('request').length,0);assert.equal(f.store.get('job','one').revision,0);});
test('independent classifier sees focused user scope only',async t=>{const f=await fixture(t);await propose(f);const seen=JSON.stringify(f.messages());assert.match(seen,/FOCUS_PURPOSE/);assert.doesNotMatch(seen,/OTHER_PRIVATE|FOCUS_TOOL_SECRET|FOCUS_ARTIFACT_SECRET/);});
test('independent classifier consent changes when endpoint route identity changes',async t=>{const f=await fixture(t),old=f.intents.publicContext().id;const job=f.store.get('job','one');f.store.put('job',{...job,routeSnapshot:f.registry.makeSnapshot('chat',[f.registry.get().profiles.find(p=>p.id==='second')],[])});assert.notEqual(f.intents.publicContext().id,old);});
test('independent classification result cannot resume unknown side effect',async t=>{const f=await fixture(t);f.store.put('effect',{id:'effect',jobId:'one',status:'unknown'});const p=await propose(f);const r=f.intents.submit({proposalId:p.id,requestId:'independent-receipt-0001'});assert.equal(r.resumeRequired,true);assert.equal(r.job.status,'paused');assert.equal(r.job.instructions[0].content,'元の文章をそのまま訂正する');});
test('independent explicit send does not call classifier',async t=>{const f=await fixture(t);f.requests.submit({requestId:'independent-receipt-0001',input:'explicit',intent:'continue',targetJobId:'one',expectedRevision:0,companionRevision:1});assert.equal(f.messages(),undefined);});
test('independent inferred side execution rejects a changed default destination',async t=>{const f=await fixture(t);f.setAnswer(reply(shape('side','one')));const p=await propose(f);const cfg=f.registry.get();f.registry.save({profiles:cfg.profiles.map(({identity,...p})=>p),routes:{main:{primary:'second',fallbacks:[]}}},cfg.revision);assert.throws(()=>f.intents.submit({proposalId:p.id,requestId:'independent-receipt-0001'}),e=>e.status===409);assert.equal(f.store.list('request').length,0);});
test('independent delayed classifier rejects concurrent focus changes without mutation',async t=>{const f=await fixture(t),release=f.hold(),pending=propose(f);f.focus.focus('two',{expectedRevision:1});release();await assert.rejects(pending,e=>e.status===409);assert.equal(f.store.list('intent-proposal').length,0);assert.equal(f.store.list('request').length,0);});
test('independent delayed classifier rejects changed job revision without mutation',async t=>{const f=await fixture(t),release=f.hold(),pending=propose(f);f.store.put('job',{...f.store.get('job','one'),revision:1});release();await assert.rejects(pending,e=>e.status===409);assert.equal(f.store.list('intent-proposal').length,0);});
test('independent revoked consent rejects classifier result before receipt',async t=>{const f=await fixture(t),release=f.hold(),pending=propose(f);f.store.value('consent-epoch',1);release();await assert.rejects(pending,e=>e.status===409);assert.equal(f.store.list('intent-proposal').length,0);});
test('independent duplicate accepted proposal submission cannot append twice',async t=>{const f=await fixture(t),p=await propose(f),body={proposalId:p.id,requestId:'independent-receipt-0001'};const a=f.intents.submit(body),b=f.intents.submit(body);assert.equal(a.job.id,b.job.id);assert.equal(b.duplicate,true);assert.equal(f.store.get('job','one').instructions.length,1);});
test('independent ambiguity is displayed data and cannot create a job',async t=>{const f=await fixture(t);f.setAnswer(reply({...shape(),ambiguous:true,question:'どちら？'}));const p=await propose(f);assert.equal(p.action,'clarify');assert.throws(()=>f.intents.submit({proposalId:p.id,requestId:'independent-receipt-0001'}),e=>e.status===409);assert.equal(f.store.list('request').length,0);});
test('LLM registry save does not cancel unrelated capability requests',async t=>{const f=await fixture(t),c=new AbortController(),llm=new AbortController();f.registry.network.active.set(c,{profileId:'cap:tts'});f.registry.network.active.set(llm,{profileId:'first'});const cfg=f.registry.get();f.registry.save({profiles:[profile('second')],routes:{main:{primary:'second',fallbacks:[]}}},cfg.revision);assert.equal(c.signal.aborted,false);assert.equal(llm.signal.aborted,true);f.registry.network.active.delete(c);f.registry.network.active.delete(llm);});
test('aborted classification does not persist a late model proposal',async t=>{const f=await fixture(t),release=f.hold(),controller=new AbortController();const pending=f.intents.propose({requestId:'independent-proposal-001',input:'side request',focusRevision:1,consent:f.intents.publicContext().id},controller.signal);controller.abort(new Error('Stopped'));release();await assert.rejects(pending,/Stopped/);assert.equal(f.store.list('intent-proposal').length,0);});
