/** Ordinary avatar HTTP parity against the compatibility service.
 * All artwork and models are generated by avatar-fixtures.mjs. The native
 * service runs with an empty PATH, an isolated home and no provider settings.
 * Build with npm run build:core && npm run build:native before running this file.
 * This is format/lifecycle coverage, not a renderer or security-boundary test.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
import {access,mkdir,mkdtemp,readdir,rm,writeFile} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
import {startServer} from '../core/server.mjs';
import {MAX_ASSETS,MAX_ASSET_BYTES,MAX_LIBRARY_BYTES,MAX_VRM_BYTES} from '../core/avatar.mjs';
import {MAX_PICTURE_BYTES,PACK_MAGIC} from '../core/avatar-inspect.mjs';
import {imageFixtures,meshFixture,shapeFixtures,vrmFixture} from './fixtures/avatar-fixtures.mjs';
import {serviceCleanup} from './helpers/service-cleanup.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const binary=path.resolve(process.env.TEPORA_NATIVE_SERVICE_BINARY||path.join(root,'native-service','target','debug',process.platform==='win32'?'tepora-native-service.exe':'tepora-native-service'));
const assetRoot='/api/avatar/assets';
const deadline=(promise,label,ms=20000)=>{
 let timer;
 return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(label)),ms);})]).finally(()=>clearTimeout(timer));
};
function pack(kind,files,name='Synthetic avatar pack'){
 const entries=Object.entries(files).map(([file,bytes])=>[file,Buffer.isBuffer(bytes)?bytes:Buffer.from(JSON.stringify(bytes))]);
 const manifest=Buffer.from(JSON.stringify({kind,name,files:entries.map(([file,bytes])=>({path:file,size:bytes.length}))}));
 const size=Buffer.alloc(4);size.writeUInt32LE(manifest.length);
 return Buffer.concat([PACK_MAGIC,size,manifest,...entries.map(([,bytes])=>bytes)]);
}
let generated;
function corpus(){
 if(generated)return generated;
 const pictures=imageFixtures(),shapes=shapeFixtures(),mesh=meshFixture(),plainMesh=meshFixture({sprites:false});
 const set={
  'imageset.json':Buffer.from(JSON.stringify({version:1,moods:{idle:'images/idle.png',happy:'images/happy.png'},talkOpen:'images/talk-open.png'})),
  ...Object.fromEntries(Object.entries(pictures).map(([name,bytes])=>['images/'+name,bytes]))
 };
 const single=(kind,bytes,filename)=>({kind,bytes,filename,files:{file:bytes}});
 const packed=(kind,files,name)=>({kind,bytes:pack(kind,files,name),filename:'project.tpak',files});
 generated={pictures,shapes,mesh,plainMesh,set,cases:[
  single('vrm',vrmFixture(),'synthetic.vrm'),
  single('vrm',vrmFixture({version:'0.x'}),'synthetic-legacy.vrm'),
  single('image',pictures['idle.png'],'窓辺のアバター.png'),
  single('image',shapes['wide.png'],'wide.png'),
  packed('imageset',set,'合成した表情セット'),
  packed('mesh',mesh,'Synthetic mesh with sprites'),
  packed('mesh',plainMesh,'Synthetic mesh without sprites')
 ]};
 return generated;
}
async function client(launchUrl,close,data){
 const launch=await fetch(launchUrl,{redirect:'manual',signal:AbortSignal.timeout(20000)});
 assert.equal(launch.status,303);
 const cookie=launch.headers.get('set-cookie')?.split(';')[0];assert.ok(cookie);
 const origin=new URL(launchUrl).origin;
 const boot=await fetch(origin+'/api/bootstrap',{headers:{Cookie:cookie},signal:AbortSignal.timeout(20000)});
 assert.equal(boot.status,200);const bootstrap=await boot.json();
 const request=(route,method='GET',body,headers={})=>fetch(origin+route,{
  method,headers:{Cookie:cookie,'X-Tepora-CSRF':bootstrap.csrf,...headers},
  ...(body===undefined?{}:{body}),signal:AbortSignal.timeout(30000)
 });
 return {request,bootstrap,close,data};
}
async function fixture(t,{agent=false}={}){
 await access(binary).catch(()=>{throw new Error(`Build the native service before this test: npm run build:native (missing ${binary})`);});
 const cleanup=serviceCleanup(t),dir=cleanup.directory(await mkdtemp(path.join(os.tmpdir(),'tepora-avatar-http-')));
 const empty=path.join(dir,'empty-path'),bundle=path.join(dir,'app.bundle.js');
 const data=[path.join(dir,'node-data'),path.join(dir,'native-data')];
 await mkdir(empty);await writeFile(bundle,'// Synthetic HTTP fixture; no browser execution.\n');
 const startNode=async()=>{
  const app=cleanup.service(await startServer({dir:data[0],runtimeFactory:()=>({decide:async()=>null,chat:async()=>({role:'assistant',content:'fixture'})})}));
  return client(app.launchUrl,app.close,data[0]);
 };
 const startNative=async()=>{
  const child=spawn(binary,['--dev-native',...(agent?['--agent']:[]),'--sidecar','--port','0','--data-dir',data[1],'--web-dir',path.join(root,'web'),'--bundle',bundle],{
   stdio:['pipe','pipe','pipe'],windowsHide:true,
   env:{PATH:empty,HOME:dir,USERPROFILE:dir,TMPDIR:dir,TEMP:dir,TMP:dir,...(process.env.SystemRoot?{SystemRoot:process.env.SystemRoot}:{})}
  });
  let stderr='',exitResult;
  child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>{stderr=(stderr+chunk).slice(-32000);});
  child.stdin.on('error',()=>{});
  const exited=new Promise(resolve=>{
   child.once('exit',(code,signal)=>{exitResult={code,signal};resolve(exitResult);});
   child.once('error',error=>{exitResult={error:error.message};resolve(exitResult);});
  });
  const lines=createInterface({input:child.stdout});
  const owned=cleanup.service({close:async()=>{
   if(!exitResult){
    child.stdin.write('shutdown\n');
    try{assert.equal((await deadline(exited,'Avatar service shutdown',10000)).code,0,stderr);}
    catch(error){child.kill('SIGKILL');await exited;throw error;}
   }
   lines.close();
  }});
  const ready=await deadline(new Promise((resolve,reject)=>{
   lines.once('line',line=>{try{resolve(JSON.parse(line));}catch(error){reject(error);}});
   exited.then(result=>reject(new Error(`Native avatar service exited before ready: ${JSON.stringify(result)} ${stderr}`)));
  }),'Native avatar service readiness');
  assert.equal(ready.type,'ready');
  return client(ready.url,owned.close,data[1]);
 };
 const maps=[new Map(),new Map()];let nextId=0;
 const pair={clients:[],data,maps,
  bind(ids){
   for(const id of ids)assert.match(id,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
   const existing=ids.map((id,i)=>maps[i].get(id));
   if(existing.some(Boolean)){assert.ok(existing.every(Boolean),'dedup identities must agree');assert.equal(existing[0],existing[1]);}
   else{const label=`asset-${++nextId}`;ids.forEach((id,i)=>maps[i].set(id,label));}
  },
  stable(value,index){
   if(typeof value==='string')return maps[index].get(value)??value;
   if(Array.isArray(value))return value.map(item=>pair.stable(item,index));
   if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,item])=>{
    if(key==='createdAt'){assert.equal(typeof item,'string');assert.equal(new Date(item).toISOString(),item);return [key,'<createdAt>'];}
    return [key,pair.stable(item,index)];
   }));
   return value;
  },
  equal(values,label){assert.deepEqual(pair.stable(values[1],1),pair.stable(values[0],0),label);return values;},
  async responses(route,method='GET',body,headers={}){
   // Sequential requests also keep the large-body quota cases memory-bounded.
   const responses=[];
   for(const [i,app] of pair.clients.entries())responses.push(await app.request(typeof route==='function'?route(i):route,method,typeof body==='function'?body(i):body,headers));
   return responses;
  },
  async json(route,method='GET',body,status=200){
   const responses=await pair.responses(route,method,body===undefined?undefined:i=>JSON.stringify(typeof body==='function'?body(i):body),{'Content-Type':'application/json'});
   return pair.equal(await parseResponses(responses,status),`${method} ${typeof route==='string'?route:'asset route'}`);
  },
  async upload(kind,bytes,filename='fixture.bin',{status=200,encodedFilename=encodeURIComponent(filename)}={}){
   const responses=await pair.responses(assetRoot,'PUT',bytes,{'Content-Type':'application/octet-stream','X-Tepora-Asset-Kind':kind,'X-Tepora-Filename':encodedFilename});
   const values=await parseResponses(responses,status);
   if(status===200)pair.bind(values.map(value=>value.asset.id));
   return pair.equal(values,`upload ${kind}: ${filename}`);
  },
  async restart(){
   await Promise.all(pair.clients.map(app=>app.close()));
   pair.clients=[await startNode(),await startNative()];
  }
 };
 pair.clients=[await startNode(),await startNative()];
 pair.equal(pair.clients.map(app=>app.bootstrap.avatarAssets),'initial avatar assets');
 pair.equal(pair.clients.map(app=>app.bootstrap.avatar),'initial avatar recipe');
 return pair;
}
async function parseResponses(responses,status){
 const values=[];
 for(const [i,response] of responses.entries()){
  const text=await response.text();
  assert.equal(response.status,status,`${i===0?'Node':'native'} response: ${text}`);
  assert.equal(response.headers.get('content-type'),'application/json; charset=utf-8');
  assert.equal(response.headers.get('cache-control'),'no-store');
  values.push(JSON.parse(text));
 }
 return values;
}
function fileRoute(ids,logicalPath='file'){
 return i=>`${assetRoot}/${ids[i]}/files/${logicalPath.split('/').map(encodeURIComponent).join('/')}`;
}
async function assertFiles(pair,saved,files){
 const ids=saved.map(value=>value.asset.id);
 for(const [logicalPath,bytes] of Object.entries(files)){
  const metadata=saved[0].asset.files.find(file=>file.path===logicalPath);assert.ok(metadata,logicalPath);
  for(const method of ['GET','HEAD']){
   const responses=await pair.responses(fileRoute(ids,logicalPath),method);
   const headers=[];
   for(const response of responses){
    assert.equal(response.status,200,`${method} ${logicalPath}`);
    headers.push(Object.fromEntries(['content-type','content-length','cache-control','x-content-type-options','content-security-policy'].map(key=>[key,response.headers.get(key)])));
    assert.equal(response.headers.get('content-type'),metadata.mime);
    assert.equal(Number(response.headers.get('content-length')),bytes.length);
    assert.deepEqual(Buffer.from(await response.arrayBuffer()),method==='HEAD'?Buffer.alloc(0):bytes);
   }
   assert.deepEqual(headers[1],headers[0],`${method} ${logicalPath} headers`);
   assert.equal(headers[1]['cache-control'],'private, max-age=3600');
  }
 }
}
async function avatarEvents(app,since,lastRevision){
 const response=await app.request(`/api/events?since=${since}`);assert.equal(response.status,200);
 assert.equal(response.headers.get('content-type'),'text/event-stream');
 const reader=response.body.getReader(),decoder=new TextDecoder(),events=[];
 let pending='',previous=since;
 try{
  for(;;){
   const {value,done}=await deadline(reader.read(),'Avatar event replay');assert.equal(done,false);
   pending+=decoder.decode(value,{stream:true});let end;
   while((end=pending.indexOf('\n\n'))!==-1){
    const block=pending.slice(0,end);pending=pending.slice(end+2);
    const lines=block.split('\n'),data=lines.filter(line=>line.startsWith('data:')).map(line=>line.slice(5).trimStart()).join('\n');
    if(!data)continue;
    const event=JSON.parse(data);
    if(!['avatar.assets','avatar.updated'].includes(event.type))continue;
    assert.deepEqual(Object.keys(event).sort(),['at','data','seq','type']);
    assert.ok(Number.isSafeInteger(event.seq)&&event.seq>previous);previous=event.seq;
    assert.equal(new Date(event.at).toISOString(),event.at);
    assert.deepEqual(lines.filter(line=>line.startsWith('id:')),[`id: ${event.seq}`]);
    assert.equal(lines.some(line=>line.startsWith('event:')),false);
    events.push({type:event.type,data:event.data});
    if(event.type==='avatar.updated'&&event.data.revision===lastRevision)return events;
   }
  }
 }finally{await reader.cancel();}
}

test('native avatar assets match HTTP metadata, ordering, logical files, bytes, HEAD and dedup',async t=>{
 const pair=await fixture(t),cases=corpus().cases;
 const initial=await pair.json(assetRoot);
 assert.deepEqual(initial[0],{assets:[],limits:{maxAssets:MAX_ASSETS,maxBytes:MAX_ASSET_BYTES,maxVrmBytes:MAX_VRM_BYTES,maxLibraryBytes:MAX_LIBRARY_BYTES}});
 for(const [index,input] of cases.entries()){
  const saved=await pair.upload(input.kind,input.bytes,input.filename);
  assert.equal(saved[0].assets.length,index+1);assert.equal(Object.hasOwn(saved[0],'existing'),false);
  for(const value of saved){
   assert.deepEqual(Object.keys(value.asset).sort(),['bytes','createdAt','files','id','kind','meta','name']);
   assert.equal(value.asset.bytes,input.bytes.length);
   assert.deepEqual(value.asset.files.map(file=>file.path),Object.keys(input.files));
   for(const file of value.asset.files){assert.deepEqual(Object.keys(file).sort(),['bytes','mime','path']);assert.equal(file.bytes,input.files[file.path].length);}
  }
  await assertFiles(pair,saved,input.files);
  const before=await pair.json(assetRoot);
  const duplicate=await pair.upload(input.kind,input.bytes,'another filename.bin');
  for(let i=0;i<2;i++){
   assert.equal(duplicate[i].existing,true);assert.deepEqual(duplicate[i].asset,saved[i].asset);
   assert.deepEqual({assets:duplicate[i].assets,limits:duplicate[i].limits},before[i]);
  }
 }
 const values=await pair.json(assetRoot);
 assert.deepEqual(values[0].assets.map(asset=>asset.kind),cases.map(input=>input.kind));
 assert.deepEqual(values[0].assets.slice(0,2).map(asset=>asset.meta.version),['1.0','0.x']);
 assert.equal(values[0].assets[2].name,'窓辺のアバター');
 assert.deepEqual(values[0].assets[4].meta,{moods:['idle','happy'],talkOpen:true,width:400,height:500});
 assert.deepEqual(values[0].assets.slice(5).map(asset=>asset.meta.sprites),[true,false]);
});

test('native avatar asset use, delete, reset, undo, event envelopes and restart match HTTP',async t=>{
 const pair=await fixture(t,{agent:true});
 const cursors=pair.clients.map(app=>app.bootstrap.seq),expectedEvents=[[],[]],saved=[];
 const inputs=['vrm','image','imageset','mesh'].map(kind=>corpus().cases.find(input=>input.kind===kind));
 for(const input of inputs){
  const values=await pair.upload(input.kind,input.bytes,input.filename);saved.push(values);
  values.forEach((value,i)=>expectedEvents[i].push({type:'avatar.assets',data:{assets:value.assets,limits:value.limits}}));
 }
 let revision=0;
 for(const [index,input] of inputs.entries()){
  const ids=saved[index].map(value=>value.asset.id);
  const worn=await pair.json('/api/avatar','PATCH',i=>({expectedRevision:revision,patch:{body:input.kind,asset:ids[i],palette:'felt'}}));revision++;
  worn.forEach((value,i)=>expectedEvents[i].push({type:'avatar.updated',data:value}));
  await pair.upload(input.kind,input.bytes,'unchanged copy.bin');
  if(index===0){
   const library=await pair.json(assetRoot);await pair.restart();
   pair.clients.forEach((app,i)=>{assert.deepEqual(app.bootstrap.avatar,worn[i]);assert.deepEqual(app.bootstrap.avatarAssets,library[i]);});
   await assertFiles(pair,saved[index],input.files);
  }
  const removed=await pair.json(i=>`${assetRoot}/${ids[i]}`,'DELETE');
  removed.forEach((value,i)=>{assert.equal(value.removed,ids[i]);expectedEvents[i].push({type:'avatar.assets',data:{assets:value.assets,limits:value.limits}});});
  const reset=await pair.json('/api/avatar');revision++;
  reset.forEach((value,i)=>{
   assert.equal(value.body,'shiro');assert.equal(value.asset,null);assert.equal(value.palette,'washi');assert.equal(value.revision,revision);
   expectedEvents[i].push({type:'avatar.updated',data:value});
  });
  const undone=await pair.json('/api/avatar/undo','POST',{expectedRevision:revision});revision++;
  undone.forEach((value,i)=>{assert.equal(value.body,'shiro');assert.equal(value.asset,null);assert.equal(value.revision,revision);expectedEvents[i].push({type:'avatar.updated',data:value});});
  await pair.json(fileRoute(ids,Object.keys(input.files)[0]),'GET',undefined,404);
  await pair.json(i=>`${assetRoot}/${ids[i]}`,'DELETE',undefined,404);
 }
 const events=await Promise.all(pair.clients.map((app,i)=>avatarEvents(app,cursors[i],revision)));
 events.forEach((value,i)=>assert.deepEqual(value,expectedEvents[i],`${i===0?'Node':'native'} avatar events, including no dedup event`));
 pair.equal(events,'avatar event payload parity');
 const finalAvatar=await pair.json('/api/avatar'),finalAssets=await pair.json(assetRoot);
 assert.deepEqual(finalAssets[0].assets,[]);await pair.restart();
 for(const [i,app] of pair.clients.entries()){
  assert.deepEqual(app.bootstrap.avatar,finalAvatar[i]);assert.deepEqual(app.bootstrap.avatarAssets,finalAssets[i]);
  assert.deepEqual(await readdir(path.join(app.data,'avatar')),[]);
 }
 const replay=await Promise.all(pair.clients.map((app,i)=>avatarEvents(app,cursors[i],revision)));
 assert.deepEqual(replay,events,'restart preserves committed avatar event history');
});

test('native avatar assets match ordinary format errors, filenames and missing-file cleanup',async t=>{
 const pair=await fixture(t),{pictures,shapes,set,mesh}=corpus();
 const missingMesh={...mesh};delete missingMesh['built/base.png'];
 const missingIdle={...set,'imageset.json':{version:1,moods:{happy:'images/happy.png'}}};
 for(const [kind,bytes] of [
  ['image',Buffer.alloc(0)],['image',Buffer.from('ordinary text is not a picture')],
  ['vrm',pictures['idle.png']],['vrm',corpus().cases[0].bytes.subarray(0,40)],
  ['image',corpus().cases[0].bytes],['imageset',pictures['idle.png']],
  ['mesh',pack('imageset',set)],['mesh',pack('mesh',missingMesh)],
  ['imageset',pack('imageset',missingIdle)],['imageset',pack('imageset',{...set,'imageset.json':Buffer.from('{unfinished')})],
  ['unknown',pictures['idle.png']]
 ])await pair.upload(kind,bytes,'incomplete fixture',{status:400});
 assert.deepEqual((await pair.json(assetRoot))[0].assets,[]);
 const unnamed=await pair.upload('image',pictures['idle.png'],'',{encodedFilename:'bad%escape'});
 assert.equal(unnamed[0].asset.name,'画像');
 const named=await pair.upload('image',shapes['tall.png'],'  縦長の合成画像.png  ');
 assert.equal(named[0].asset.name,'縦長の合成画像');
 const ids=named.map(value=>value.asset.id);
 await pair.json(fileRoute(ids,'not-present.png'),'GET',undefined,404);
 await pair.json(fileRoute(['11111111-1111-4111-8111-111111111111','11111111-1111-4111-8111-111111111111']),'GET',undefined,404);
 for(const [i,app] of pair.clients.entries())await rm(path.join(app.data,'avatar',ids[i],'0'));
 const missing=await pair.json(fileRoute(ids),'GET',undefined,404);
 assert.equal(missing[0].error,'素材のファイルが見つかりません。');
 const removed=await pair.json(i=>`${assetRoot}/${ids[i]}`,'DELETE');
 assert.equal(removed[0].assets.length,1);
});

test('native avatar library count quota, existing uploads and reclaimed slots match HTTP',async t=>{
 const pair=await fixture(t),set=corpus().set,saved=[];
 for(let i=0;i<MAX_ASSETS;i++)saved.push(await pair.upload('imageset',pack('imageset',set,`Synthetic set ${i+1}`)));
 const full=await pair.json(assetRoot);assert.equal(full[0].assets.length,MAX_ASSETS);
 const duplicate=await pair.upload('imageset',pack('imageset',set,'Synthetic set 1'));
 duplicate.forEach((value,i)=>{assert.equal(value.existing,true);assert.deepEqual(value.asset,saved[0][i].asset);});
 const extra=pack('imageset',set,'Synthetic set beyond the limit');
 const refused=await pair.upload('imageset',extra,'extra.tpak',{status:413});
 assert.equal(refused[0].error,`素材は${MAX_ASSETS}件までです。使わないものを削除してください。`);
 assert.deepEqual(await pair.json(assetRoot),full);
 await pair.json(i=>`${assetRoot}/${saved[7][i].asset.id}`,'DELETE');
 const replacement=await pair.upload('imageset',extra);
 assert.equal(replacement[0].assets.length,MAX_ASSETS);
 assert.equal(replacement[0].assets.at(-1).id,replacement[0].asset.id);
});

test('native avatar per-file and request-body size quotas match HTTP without saving bytes',{timeout:120000},async t=>{
 const pair=await fixture(t),picture=corpus().pictures['idle.png'];
 // These are generated inert byte buffers, never real artwork or user files.
 // Do not fill a 1 GiB library just to check its aggregate quota here.
 for(const [kind,size,message] of [
  ['image',MAX_PICTURE_BYTES+1,'画像は16MBまでです。'],
  ['vrm',MAX_VRM_BYTES+1,'VRMファイルは80MBまでです。'],
  ['image',MAX_ASSET_BYTES+1,'ファイルが大きすぎます。']
 ]){
  const bytes=Buffer.alloc(size);picture.copy(bytes);
  const values=await pair.upload(kind,bytes,'large synthetic fixture',{status:413});
  assert.equal(values[0].error,message);
  assert.deepEqual((await pair.json(assetRoot))[0].assets,[]);
 }
 for(const app of pair.clients)assert.deepEqual(await readdir(path.join(app.data,'avatar')).catch(error=>{if(error.code==='ENOENT')return [];throw error;}),[]);
});
