use serde_json::Value;
use tokio::sync::oneshot;

#[derive(Debug)]
pub enum SessionQuery {
    GetStatus {
        session_id: String,
        reply_to: oneshot::Sender<String>,
    }
}

#[derive(Debug, Clone)]
pub enum SessionCommand {
    /// Command to process a new user message in a session
    ProcessMessage {
        session_id: String,
        message: String,
        mode: String,
        attachments: Vec<Value>,
        thinking_budget: u8,
        agent_id: Option<String>,
        agent_mode: Option<String>,
        skip_web_search: bool,
    },
    /// Command to stop any ongoing generation in a session
    StopGeneration {
        session_id: String,
    },
    /// Command to resolve a pending tool approval request in actor mode.
    ToolApprovalResponse {
        session_id: String,
        request_id: String,
        approved: bool,
    },
    /// Command to shut down the session actor
    Shutdown {
        session_id: String,
    },
}

#[derive(Debug, Clone, serde::Serialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum SessionEvent {
    /// A single token generated by the LLM
    Token { session_id: String, text: String },
    /// Thought/reasoning content produced separately from answer tokens
    Thought { session_id: String, content: String },
    /// A status update or step completion
    Status { session_id: String, message: String },
    /// Error occurred during processing
    Error { session_id: String, message: String },
    /// Node execution completed, may include tool call information
    NodeCompleted {
        session_id: String,
        #[serde(rename = "nodeId")]
        node_id: String,
        output: Value,
    },
    /// Memory generation is starting or has completed
    MemoryGeneration {
        session_id: String,
        status: String, // "started" or "completed"
    },
    /// Generation completely finished
    GenerationComplete { session_id: String },
}
