/** User-initiated PCM capture only. Never use browser SpeechRecognition (may send audio to a cloud). */
export class VoiceCapture {
 constructor(){this.stream=null;this.context=null;this.node=null;this.frames=[];this.timer=null;}
 async start(onLimit){if(this.stream)throw new Error('録音中です。');if(!navigator.mediaDevices?.getUserMedia)throw new Error('この表示環境ではマイクを利用できません。ローカルアプリを起動してください。');this.stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true},video:false});
  try{this.context=new AudioContext();await this.context.resume();this.frames=[];const code=`class TeporaPCM extends AudioWorkletProcessor{process(inputs){const a=inputs[0]?.[0];if(a)this.port.postMessage(a.slice());return true;}}registerProcessor('tepora-pcm',TeporaPCM);`;const url=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));try{await this.context.audioWorklet.addModule(url);}finally{URL.revokeObjectURL(url);}this.node=new AudioWorkletNode(this.context,'tepora-pcm');this.node.port.onmessage=e=>this.frames.push(e.data);const source=this.context.createMediaStreamSource(this.stream),mute=this.context.createGain();mute.gain.value=0;source.connect(this.node);this.node.connect(mute);mute.connect(this.context.destination);this.timer=setTimeout(()=>onLimit?.(),60000);
  }catch(e){await this.cancel();throw e;}
 }
 async stop(){if(!this.context)throw new Error('録音を開始してください。');clearTimeout(this.timer);this.node?.disconnect();this.stream?.getTracks().forEach(t=>t.stop());const rate=this.context.sampleRate;await this.context.close();this.stream=null;this.context=null;const length=this.frames.reduce((n,a)=>n+a.length,0);if(length<rate*.2)throw new Error('録音が短すぎます。もう一度お話しください。');const out=new ArrayBuffer(44+length*2),v=new DataView(out);const str=(p,s)=>{for(let i=0;i<s.length;i++)v.setUint8(p+i,s.charCodeAt(i));};str(0,'RIFF');v.setUint32(4,36+length*2,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,length*2,true);let offset=44;for(const a of this.frames)for(const f of a){v.setInt16(offset,Math.max(-1,Math.min(1,f))*(f<0?32768:32767),true);offset+=2;}this.frames=[];return new Blob([out],{type:'audio/wav'});}
 async cancel(){clearTimeout(this.timer);this.node?.disconnect();this.stream?.getTracks().forEach(t=>t.stop());await this.context?.close();this.stream=null;this.context=null;this.frames=[];}
}
