import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import "./i18n";
import { AppEntry } from "./app/entry";

import { getSessionToken } from "./utils/sessionToken";
import { logger } from "./utils/logger";

import { backendReady, isDesktop, startSidecar } from "./utils/sidecar";

// Start the backend sidecar and wait for it before mounting React
async function init() {
	// Initialize transport mode early so websocketStore.connect() chooses
	// IPC-first in desktop mode before SettingsContext config fetch completes.
	if (typeof window !== "undefined" && !window.__TRANSPORT_MODE__) {
		window.__TRANSPORT_MODE__ = isDesktop() ? "ipc" : "websocket";
	}

	// Start sidecar (non-blocking)
	startSidecar();

	// Wait for backend to be ready before loading token (desktop mode)
	// This ensures we get the fresh token generated by the backend
	if (isDesktop()) {
		logger.log("[Main] Desktop mode detected, waiting for backend ready...");
		await backendReady;
		logger.log("[Main] Backend ready, loading session token...");
	}

	try {
		await getSessionToken();
	} catch (error) {
		logger.warn("[Main] Failed to load session token:", error);
	}

	const rootElement = document.getElementById("root");
	if (!rootElement) throw new Error("Failed to find the root element");

	ReactDOM.createRoot(rootElement).render(
		<React.StrictMode>
			<AppEntry />
		</React.StrictMode>,
	);
}

init();
