import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.tsx";
import "./index.css";
import "./i18n";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import ErrorBoundary from "./components/ui/ErrorBoundary";
import { SettingsProvider } from "./context/SettingsContext";
import { ThemeProvider } from "./context/ThemeContext";

import { getSessionToken } from "./utils/sessionToken";

const queryClient = new QueryClient();

import { backendReady, isDesktop, startSidecar } from "./utils/sidecar";

// Start the backend sidecar and wait for it before mounting React
async function init() {
	// Start sidecar (non-blocking)
	startSidecar();

	// Wait for backend to be ready before loading token (desktop mode)
	// This ensures we get the fresh token generated by the backend
	if (isDesktop()) {
		console.log("[Main] Desktop mode detected, waiting for backend ready...");
		await backendReady;
		console.log("[Main] Backend ready, loading session token...");
	}

	try {
		await getSessionToken();
	} catch (error) {
		console.warn("[Main] Failed to load session token:", error);
	}

	const rootElement = document.getElementById("root");
	if (!rootElement) throw new Error("Failed to find the root element");

	ReactDOM.createRoot(rootElement).render(
		<React.StrictMode>
			<ErrorBoundary>
				<QueryClientProvider client={queryClient}>
					<SettingsProvider>
						<ThemeProvider>
							<App />
						</ThemeProvider>
					</SettingsProvider>
					<ReactQueryDevtools initialIsOpen={false} />
				</QueryClientProvider>
			</ErrorBoundary>
		</React.StrictMode>,
	);
}

init();
